openapi: 3.0.1
info:
  title: Eclipse Dataspace Connector Registration Service
  version: 0.0.1
paths:
  /registry/participants:
    get:
      tags:
      - Registry
      operationId: listParticipants
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Participant'
components:
  schemas:
    Participant:
      type: object
      properties:
        name:
          type: string
        url:
          type: string
        supportedProtocols:
          type: array
          items:
            type: string
